### ISSUE TITLE
Helm-cscope not listed on MELPA?

### ISSUE THREAD

**Issue by ReneFroger** [sergey-pashaev/helm-cscope#3]
Hi Sergey, thanks for sharing this package! It's appreciated. 

However, I couldn't find it on MELPA. Could this perhaps be listed on MELPA?

Thanks in advance!

**Comment by sergey-pashaev** [comment]
As you might guess, I have long ceased to use this package. Actually, there is some helm-cscope package on MELPA - http://melpa.org/#/helm-cscope . Check it out. It looks maintained.

**Comment by ReneFroger** [comment]
Thanks. Never guessed I would ever got a response.
